import type { Config } from "tailwindcss";

// Token names/values copied verbatim from the Stitch-generated design system
// (projects/661045816018978058) so screen markup can port over 1:1 without translation.
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./screens/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-container": "#efeeeb",
        "secondary-fixed": "#ffdbd2",
        "tertiary-fixed": "#ffdcc3",
        background: "#fbf9f6",
        "surface-dim": "#dbdad7",
        "on-tertiary-fixed": "#2f1500",
        "on-primary-fixed-variant": "#284b59",
        outline: "#72787b",
        "surface-container-highest": "#e4e2df",
        "on-background": "#1b1c1a",
        "primary-container": "#163b48",
        "surface-container-high": "#eae8e5",
        "on-surface-variant": "#41484b",
        "on-secondary-fixed-variant": "#7c2e19",
        "secondary-fixed-dim": "#ffb4a1",
        "outline-variant": "#c1c7cb",
        "primary-fixed": "#c4e8f9",
        "inverse-surface": "#30312f",
        "surface-bright": "#fbf9f6",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-secondary-container": "#742814",
        "on-primary-container": "#82a5b4",
        "error-container": "#ffdad6",
        primary: "#002530",
        "on-tertiary-fixed-variant": "#6e3900",
        surface: "#fbf9f6",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#572c00",
        "surface-container-low": "#f5f3f0",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1c1a",
        "on-tertiary-container": "#ec861d",
        secondary: "#9a442d",
        "surface-variant": "#e4e2df",
        "surface-tint": "#416371",
        "tertiary-fixed-dim": "#ffb77d",
        "inverse-primary": "#a8ccdc",
        "inverse-on-surface": "#f2f0ed",
        "on-primary-fixed": "#001f29",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#a8ccdc",
        "secondary-container": "#fc9174",
        "on-secondary-fixed": "#3c0800",
        tertiary: "#371a00",
        success: "#2d7a68",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        caption: ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": [
          "26px",
          { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-md": ["14px", { lineHeight: "18px", fontWeight: "500" }],
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        caption: ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      spacing: {
        "space-xs": "0.5rem",
        "card-pad-lg": "1.5rem",
        "margin-desktop": "3rem",
        "space-2xs": "0.25rem",
        "space-sm": "0.75rem",
        "touch-target-min": "3rem",
        "gutter-tablet": "1.5rem",
        "margin-mobile": "1.25rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "card-pad-md": "1.25rem",
        "space-md": "1rem",
        "gutter-desktop": "2rem",
        "space-xl": "2rem",
        "margin-tablet": "2rem",
        "space-2xl": "3rem",
        "card-pad-sm": "1rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        "rlap-1": "0 2px 4px rgba(22, 59, 72, 0.03), 0 8px 24px rgba(22, 59, 72, 0.05)",
        "rlap-2": "0 6px 16px rgba(22, 59, 72, 0.06), 0 16px 36px rgba(22, 59, 72, 0.08)",
        "rlap-3": "0 12px 32px rgba(22, 59, 72, 0.12), 0 24px 64px rgba(22, 59, 72, 0.14)",
      },
    },
  },
  plugins: [],
};

export default config;
